name: CI/CD  Equipo Amarillo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build app
        run: npx nx run cartelera-cine:build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: npx nx run cartelera-cine:test

  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run lint
        run: npx nx run cartelera-cine:lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Build app for deployment
        run: npx nx run cartelera-cine:build

      # Este paso está comentado hasta que se configure el servicio de despliegue
      # - name: Deploy to Hosting Service
      #   run: |
      #     # Aquí iría el comando para desplegar la app al servicio de hosting
