name: Deploy CineApp-ventaBoletos

on:
  push:
    branches:
      - main
    paths:
      - apps/venta-boletos/**
      - apps/back-venta-boletos/**
  pull_request:
    branches:
      - main
    paths:
      - apps/venta-boletos/**
      - apps/back-venta-boletos/**

jobs:
  build_front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run venta-boletos:build  --no-cloud

  test_front:
    needs: [build_front]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run venta-boletos:test  --no-cloud

  lint_front:
    needs: [test_front]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run venta-boletos:lint  --no-cloud

  build_back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run back-venta-boletos:build  --no-cloud

  test_back:
    needs: [build_back]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run back-venta-boletos:test  --no-cloud

  lint_back:
    needs: [test_back]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npx nx run back-venta-boletos:lint  --no-cloud

  build_and_deploy:
    needs: [lint_front, lint_back]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npx nx run venta-boletos:build  --no-cloud
      - name: Deploy to Firebase (Production)
        if: ${{ github.event_name == 'push' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN_CINE_UDONE }}'
          channelId: live
          projectId: CineUdone
          target: venta-boletos
      - name: Deploy to Firebase (Staging)
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN_CINE_UDONE  }}'
          channelId: staging
          projectId: CineUdone
          target: venta-boletos